# Feed / Atom
domain: front-end.js.org
author: Jorge Moliner
email: email@whoisjorge.me

# ############# #
# Configuración #
# ############# #
lang                      : es
locale                    : es-ES
url                       : https://front-end.js.org

# Desarrollo en http://localhost:4000/front-end/
# `bundle exec jekyll serve --baseurl /front-end`
# baseurl                   : /front-end

# GitHub metadata
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository                : whoisjorge/front-end



# Información Básica
title                     : Front-end
description               : Recopilación de snippets y apuntes sobre tecnología, desarrollo web front-end y lenguajes de programación
gh_repo                   : https://github.com/whoisjorge/front-end/

# External
google_analytics:
disqus:
  shortname: front-end-cheatsheets



# Outputting
permalink                 : date
paginate_path             : /:num/
timezone                  : Europe/Madrid
parentsite                : https://front-end.js.org
permalink                 : /:categories/:title/

# Markdown - conversion
markdown                  : kramdown
highlighter               : rouge
lsi                       : false
excerpt_separator         : "\n\n"


# Gemas
plugins:
  #
  # https://github.com/jekyll/jekyll-assets
  - jekyll-assets
  #
  #
  # https://github.com/jekyll/jekyll-feed
  - jekyll-feed
  # https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap
  # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-seo-tag
  # https://github.com/jekyll/jekyll-gist
  - jekyll-gist



# Reglas de procesamiento
include:
  # - .htaccess
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
